\documentclass[final]{beamer} % beamer 3.10: do NOT use option hyperref={pdfpagelabels=false} !
  %\documentclass[final,hyperref={pdfpagelabels=false}]{beamer} % beamer 3.07: get rid of beamer warnings
  \mode<presentation> { \usetheme{UFPoster} }
  \usepackage[english]{babel}
  \usepackage[latin1]{inputenc}
  \usepackage{amsmath,amsthm, amssymb, latexsym}
  \usefonttheme[onlymath]{serif}
  \boldmath
  \usepackage[orientation=portrait,size=custom,height=114,width=114,scale=1.1,debug]{beamerposter}                       % e.g. for DIN-A0 poster
  \title{School-Located Influenza Vaccination (\emph{SLIV}) Programs\\ Are a Cost-Saving Opportunity
  for Private Insurers}
  \author{Carl A. B. Pearson, Cuc Tran, Dennis Chao}
  \institute[EPI-UF]{Emerging Pathogens Institute, University of Florida}
  \date{\today}
  \newcommand{\spaceProp}{0.02}
  \newcommand{\spacer}{\begin{column}{\spaceProp\paperwidth}\end{column}}
  
  \newenvironment{oneCol}{\begin{column}[t]{0.3\paperwidth}}{\end{column}}
  \newenvironment{threeCol}{\begin{column}[t]{0.64\paperwidth}}{\end{column}}
  \setbeamertemplate{caption}[numbered]
\begin{document}
\SweaveOpts{concordance=TRUE}
  \begin{frame}{}
    \begin{columns}[t]
    \spacer{}
    \begin{oneCol}
    \begin{block}{Background}
Schools have dense, well-mixed, relatively influenza naive populations, making them critical to influenza spread between households.  Vaccinating this route can prevent cases in other demographics.  {\bfseries S}chool {\bfseries L}ocated {\bfseries I}nfluenza {\bfseries V}accination ({\bfseries SLIV}) programs target this opportunity.  Because SLIV programs target dense populations, they can have low administrative overhead and marginal cost reduces to only vaccine doses.
    \end{block}
    \begin{block}{Research Question}
Private health insurers, unlike individuals, can realize the indirect benefits of {\emph community immunity} via aggregate reduced treatment payouts, meaning SLIV programs could be voluntarily funded rather than via tax-supported public health departments. The question is: {\bfseries When do SLIV programs net private insurance savings?}
    \end{block}
    \begin{block}{Materials}
\begin{itemize}
\item Reported insurance payouts for Influenza-Like Illness (\emph{ILI}),
\item Alachua County, FL program administration and vaccine dose costs,
\item FluTE stochastic influenza simulator
\end{itemize}

    \end{block}
    \begin{block}{Methods}

We use FluTE to simulate epidemics across SLIV campaign coverage rates, sampling across two scenario axes: vaccine efficacy (well-matched or not) and transmissibility ($R\_0 = (1.2, 1.3, 1.4)$).  Results are aggregated to mean attack rates on broad age categories: pre-school, school age, young adults, middle ages, and seniors.  Those attack rates are then combined with age-specific insurer costs by outcome (e.g., outpatient, hospitalization, death), admin (fixed per capita) cost, and vaccine cost (flexible by dose).

We can then estimate coverage which maximizes savings.

    \end{block}
    \begin{block}{References}
      \nocite{*} % Insert publications even if they are not cited in the poster
      \small{\bibliographystyle{unsrt}
      \bibliography{biblio}\vspace{0.75in}}
    \end{block}
    \end{oneCol}
    \spacer{}
    \begin{threeCol}
    \begin{block}{Results}
    \begin{columns}
    \begin{oneCol}
      \begin{figure}
        %\includegraphics[width=1.0\linewidth]{dataReview.png}
      \end{figure}   
    \end{oneCol}
    %\spacer{}
    \begin{oneCol}
      \begin{figure}
        %\includegraphics[width=1.0\linewidth]{maxComp.png}
      \end{figure}   
    \end{oneCol}
    %\spacer{}
    \begin{oneCol}
      \begin{figure}
        %\includegraphics[width=1.0\linewidth]{maxEdges.png}
      \end{figure}   
    \end{oneCol}
    \end{columns}
    Blah 
    \end{block}
    
    \begin{block}{Results}
    \begin{columns}
    \begin{oneCol}
      \setcounter{figure}{0}
      \begin{figure}
        \caption{Contacts Binned Daily}
        %\includegraphics[width=1.0\linewidth]{out1.png}
      \end{figure}
      \setcounter{figure}{3}
      \begin{figure}
        %\includegraphics[width=1.0\linewidth]{out90.png}
        \caption{Contacts Binned Quarterly}
      \end{figure}  
    \end{oneCol}
    %\spacer{}
    \begin{oneCol}
      \setcounter{figure}{1}
      \begin{figure}
        \caption{Contacts Binned Weekly}
        %\includegraphics[width=1.0\linewidth]{out7.png}
      \end{figure}
      \setcounter{figure}{4}
      \begin{figure}
        %\includegraphics[width=1.0\linewidth]{out180.png}
        \caption{Contacts Binned Biannually}
      \end{figure}  
    \end{oneCol}
    %\spacer{}
    \begin{oneCol}
      \setcounter{figure}{2}
      \begin{figure}
        \caption{Contacts Binned Monthly}
        %\includegraphics[width=1.0\linewidth]{out30.png}
      \end{figure}
      \setcounter{figure}{5}
      \begin{figure}
        %\includegraphics[width=1.0\linewidth]{out365.png}
        \caption{Contacts Binned Yearly}
      \end{figure}  
    \end{oneCol}
    \end{columns}
    \end{block}
    \begin{block}{Conclusions \&\ Future Work}

SLIV programs reduce cost only in some scenarios.  For lower transmissibility outbreaks, maximum benefit occurs well below the government recommended coverage.  Counter-intuitively, SLIV is more beneficial when the vaccine is less efficacious: since the background coverage for a well-matched vaccine avoids most costs already, SLIV gains do not outpace cost of running program.

In future analysis, we plan to address:
\begin{itemize}
\item FluTE is not practically flexible to adapt to particular communities.  The runs simulate Los Angeles, CA, while the costs are for Alachua County, FL.
\item Improving cost data by disaggregation
\item Consider other cost models, *e.g.* employers recovering lost work hours.
\end{itemize}
    \end{block}
    \end{threeCol}
    \spacer{}
    \end{columns}
  \end{frame}
  \end{document}
